// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Img from "./Img.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

import './App.css'
;

function App$App(Props) {
  return React.createElement(React.Suspense, {
              children: React.createElement("div", undefined, React.createElement(Img.make, {
                        src: "https://rescript-lang.org/static/rescript_logo_black.svg"
                      }), React.createElement("div", {
                        className: "esbuild"
                      }, React.createElement(Img.make, {
                            src: "https://esbuild.github.io/favicon.svg"
                          }), React.createElement("div", undefined, "esbuild"))),
              fallback: React.createElement(React.Fragment, undefined)
            });
}

var App = {
  make: App$App
};

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(App$App, {}), root);
}

export {
  App ,
  
}
/*  Not a pure module */
